### ISSUE TITLE
[DISCUSSION] ESM Support

### ISSUE THREAD

**Issue by hefler** [junminahn/node-font2base64#4]
Hi! 👋 
I've forked and converted this lib to ESM [see here](https://github.com/hefler/node-font2base64/tree/esm) as I have a project that uses ESM.

I'm wondering if there are any plans in making this available to others too. It could be as an `esm` branch, or convert it to TS, or use `.mjs` extension. Any thoughts or plans on it?
If there're no plans I can create it as package. I just wanted to run it by you first.

Also thanks for making this library!

**Comment by junminahn** [comment]
Hi @hefler, thank you for making use of this library and contributing on this.

I do have a plan to convert the codebase into `Typescript(TS)` to support type information for other `Typescript` projects, and
haven't had a chance to work on it. To support the current users, it will be still `cjs` converted implementation files with `.d.ts files` when published though. Does it still meet your requirement? otherwise, I might take a look at the way to build Typescript files into two separate formats; `cjs` and `esm`.

Thanks!

**Comment by hefler** [comment]
It's possible to keep support for both by having `.mjs` files for `esm` and keeping `cjs` as `.js`, node does the rest. The inconvenience is to maintain both files. In that case moving to TypeScript makes more sense.
Perhaps, have a look at this article https://antfu.me/posts/publish-esm-and-cjs or if you don't want to go through the whole thing check out [tsup](https://tsup.egoist.dev/). It seems straight forward — fateful last words… 😅

I hope it helps

**Comment by junminahn** [comment]
@hefler thanks again for the direction; as you suggested I used `tsup` to bundle `cjs` and `esm` in one go; I really liked it.
please try `node-font2base64@0.9.2` for the new version that includes the type declaration and `esm` support.
https://www.npmjs.com/package/node-font2base64

P.S. I couldn't upgrade one of the dependencies', `file-type`, version to the latest version since it does not support the `CJS Package` any longer from version 17.

Thanks!

**Comment by hefler** [comment]
@junminahn you legend!!

On a tiny side note: Is `file-type` really necessary? My impression is that the library is so specific that there's a handful of mime types to be used.
But I don't wanna drag too long with petty comments.
Thanks a lot for looking into the issue so quick.

**Comment by junminahn** [comment]
@hefler sorry for the late response and thank you for the suggestion! :)
I believe `file-type` is used to check the `magic number` of the buffer and avoid loading the whole file.
Let me close this ticket and will take a look `file-type`'s implementation to see if we can drop it.
